GPS testing and UML diagram
Redback-Operations/redback-orion pull request #2
Opened 2024-04-14 02:19 UTC by ishaan2307

2024-04-25 06:07 UTC, MarsImmortal commented on README.md
> -IoT and Data science code
this is the orignal read me file so dont edit this.

2024-04-25 06:08 UTC, MarsImmortal requested changes
Have a meeting with me regarding creating a pull req. Need to address some changes.

2024-04-25 06:18 UTC, MarsImmortal commented
Ishaan just delete the branch you have created and pull the repo on your device again so its up to date. Further make another folder for IOT and add the sensor name over there in order to make it a bit systematic (in main branch). Text me on teams if you are facing any issues.

2024-04-26 03:10 UTC, cybermehak approved these changes
Already reviewed!

2024-04-27 04:18 UTC, closed without merging