Add files via upload
Redback-Operations/redback-orion pull request #3
Opened 2024-04-14 17:22 UTC by Ayush-Som

The first basic code that I developed while researching the project.
Description: This Python script uses Flask and OpenCV to create a simple web server that streams video from a webcam. The script initializes video capture with OpenCV, captures frames from the webcam, encodes them as JPEG images, and sends them over HTTP as a continuous stream. The video stream is made accessible via a web route (`/video`). When accessed, the server sends the video frames in a format suitable for real-time streaming on web browsers. The Flask app is set to run on all interfaces on port 5000 with debug mode enabled.

2024-04-25 08:02 UTC, MarsImmortal reviewed
Hey ayush your code according to my understanding receives data published on sensor topic and stored it on mango db. If I am not wrong from what i remember  we need to transport the full video which from my experience might not be possible without converting the existing mp4 file. Can you let me know on how you plan to deliver that aim of the project. And if you have already implemented it that would be more than helpfull for the team just test me on team chat and share the code on git itself.

2024-04-25 08:06 UTC, MarsImmortal commented
One thing that will be quite helpful for me to understand on what you are upto is  description. For that you wanna have two things in your description for pull request. First, why you have used the following things to implement (that you have mentioned so ignore this). Second, what impact is this making to the company ? (try to relate it with the real scenario of project). Otherwise your progress seems good but needs some improvement. Thank you.

2024-04-25 08:10 UTC, MarsImmortal reviewed
Hope your issue is solved with raspberry pi os. This code looks quite helpful just let me know whenever you are able to test this and find any results. Also I am curious to know how can we modify this code or make changes in the coding environment to livestream the vid on the web.

2024-04-25 08:11 UTC, MarsImmortal commented
One last thing ayush try to have commit messages on your commits this allows me to navigate through the files quicker further allowing me to give feedbacks faster and merge pull requests.

2024-04-26 04:34 UTC, cybermehak requested changes

2024-04-26 04:34 UTC, cybermehak commented on pi_cam_testing_final.py
> +@app.route('/video_feed')
The code currently lacks authentication and authorization mechanisms.
Sensitive endpoints such as /video_feed should require authentication to prevent unauthorized access.
**Recommendation:** Implement authentication and authorization mechanisms using Flask's middleware. Use environment variables for storing authentication credentials. DO NOT use hard coded credentials for this!!

2024-04-26 04:34 UTC, cybermehak commented on pi_cam_testing_final.py
> +    # This route returns the streaming response using the generator function
```
from flask import Flask, Response, make_response

response = make_response(generate_frames())
response.headers['Content-Security-Policy'] = "default-src 'self'"
return response
```

2024-04-26 04:34 UTC, cybermehak commented on pi_cam_testing_final.py
> +    # Initialize the camera
Instead of printing error messages to the console, use Flask's **error handling** mechanism to return appropriate HTTP responses. This ensures that clients receive meaningful feedback.

2024-04-26 04:34 UTC, cybermehak commented on pi_cam_testing_final.py
> +    # Initialize the camera
```
from flask import abort

# Inside generate_frames()
if not camera.isOpened():
    abort(500, "Failed to open camera")

```

2024-04-26 04:34 UTC, cybermehak commented on pi_cam_testing_final.py
> +    app.run(host='0.0.0.0', port=5000, threaded=True)
Enable **HTTPS support** to encrypt communication between clients and the server. This enhances security, especially if the application is deployed in a production environment.

2024-04-26 04:34 UTC, cybermehak commented on pi_cam_testing_final.py
> +    app.run(host='0.0.0.0', port=5000, threaded=True)
```
# Will need to obtain a self-signed SSL certificate
app.run(host='0.0.0.0', port=5000, threaded=True, ssl_context=('cert.pem', 'key.pem'))
```

2024-04-26 04:34 UTC, cybermehak commented on pi_cam_testing_final.py
I have provided some suggestions and improvements to enhance the security and efficiency of the code.
If you have any doubts while implementing the provided suggestions, do reach out to me on MS Teams.
You might have to search "how to obtain a self-signed SSL certificate" and "how to apply a login mechanism by using environmental variables".

2024-04-27 16:03 UTC, cybermehak requested changes
Implementing the suggested changes should be enough to enhance the security. One thing noticed on reviewing the 5 code files was that input validation, error handling and avoiding hard coding sensitive information are secure coding practices which should be adopted. Rest are measures from cyber security point of view.

2024-05-14 01:38 UTC, cybermehak approved these changes
The code is now prepared for merging, as all necessary modifications have been seamlessly integrated.

2024-05-16 05:47 UTC, ishaan2307 approved these changes
Code already approved by Mehak.

2024-05-16 05:47 UTC, merged