Added Face-Detection-API Code and Documentation
Redback-Operations/redback-orion pull request #35
Opened 2024-09-13 03:27 UTC by mustafaT96

Changes are made in:
redback-orion\Crowd_Monitoring

Added:
redback-orion\Crowd_Monitoring\Face & Facial Features Detection\Code
redback-orion\Crowd_Monitoring\Face & Facial Features Detection\Documentation

In order to get model and weight files, use the link provided below. Test results are also in the given link.
https://github.com/mustafaT96/Face-Detection-API.git

2024-09-14 05:28 UTC, sumituiet requested changes

2024-09-14 05:28 UTC, sumituiet commented on Crowd_Monitoring/Face & Facial Features Detection/Code/app.py
> +async def process_frame(file: UploadFile = File(...)):
Please add the error handling for the apis using try and except

2024-09-14 05:28 UTC, sumituiet commented on Crowd_Monitoring/Face & Facial Features Detection/Code/config.py
> +# config.py
Please use secrets file instead of config.py for loading the urls and paths for the files for better interaction and security. 
please use dotenv package to handle secretes .

2024-09-16 06:28 UTC, kcf-jackson commented
Thanks for the good work. The documentation is well structured. @mustafaT96 and Abdul

- Please removes space in the folder and file name. See the README.md at the top level of this repo for files / folder naming convention. 
- You have duplicated extension name in `Documentation/Requirements.txt.txt`. Also, it's not actually a requirements.txt. You should use command like `pip freeze > requirements.txt` to generate the file.
- You have missing dependency 'dlib'
- For "Document 2.0.md", 
    - about the project structure, please specify the full path to the files. 
    - please specify the data source.
    - please provide the command to install the dependencies, i.e. `pip install -r requirements.txt`
    - please provide the command to install uvicorn. It seems like your setup requires a Linux environment? If so, please list it as a requirement in the documentation.
    - Instead of asking user to copy the data to the root directory, you could
        - structure the project directory that way, or
        - provide the command that does the copying, or 
        - prepare the makefile that does the copying, or
        - (preferred) change your code to follow the directory structure you have. (I am having quite a few path issues).
     - please include screenshots in the documentation.

2024-09-18 12:53 UTC, Ingabreezy reviewed
No security vulnerabilities detected

2024-09-19 08:34 UTC, Ingabreezy commented
@mustafaT96 kindly tag me for approval once changes have been made

2024-10-23 07:33 UTC, ben-AI-cybersec commented
Requested changes not completed. Closing PR.

2024-10-23 07:33 UTC, closed without merging