Added Player_Tracking_Code
Redback-Operations/redback-orion pull request #51
Opened 2024-12-03 01:12 UTC by AbstractSahil

2024-12-13 03:41 UTC, RichardWhellum requested changes
Please fix validation issue for RealTimeVideo_Dashboard/app.py.

2024-12-13 03:41 UTC, RichardWhellum commented on RealTimeVideo_Dashboard/app.py
The uploaded video files are not validated beyond their extensions, which poses a security risk. Attackers could upload malicious files disguised as valid video formats. Consider implementing content validation, possibly using a library like python-magic to ensure the uploaded file matches the expected format.

2024-12-15 02:18 UTC, AbstractSahil commented
I have checked the code, and it is still working at my end, just refer to the below demonstration video for the same - https://youtu.be/gDBXJk7ZVfU

2025-01-20 06:14 UTC, ben-AI-cybersec commented
Imports a submodule instead of adding player tracking code. Closing as this isn't appropriate for work that belongs in this repo.

2025-01-21 03:37 UTC, ben-AI-cybersec commented
Fixed merge conflicts manually, closing this PR

2025-01-21 03:37 UTC, closed without merging