Added face_detection folder
Redback-Operations/redback-orion pull request #52
Opened 2024-12-08 16:50 UTC by yuekaicn

2024-12-13 03:55 UTC, RichardWhellum requested changes

2024-12-13 03:55 UTC, RichardWhellum commented on Crowd_Monitoring/face_detection/code/image_prediction.py
The code does not sanitise or validate file paths (img_path and output_path), which could potentially lead to injection attacks if malicious inputs are provided.

2024-12-14 08:51 UTC, yuekaicn commented on Crowd_Monitoring/face_detection/code/image_prediction.py
Added security checks for file paths.

2024-12-15 00:28 UTC, RichardWhellum approved these changes
Very nice. Thank you.

2024-12-15 00:29 UTC, merged